/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Alexandra
 */
public class CuentaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CuentaUsuario
     */
    public CuentaUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblcuenta = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lblsald = new javax.swing.JLabel();
        lblseleccionar = new javax.swing.JLabel();
        lblvalor = new javax.swing.JLabel();
        lbsaldo = new javax.swing.JLabel();
        rdbdeposito = new javax.swing.JRadioButton();
        rdbretiro = new javax.swing.JRadioButton();
        txtvalor = new javax.swing.JTextField();
        btnregistrarse = new javax.swing.JButton();
        lblsaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        lblcuenta.setFont(new java.awt.Font("Trebuchet MS", 3, 26)); // NOI18N
        lblcuenta.setForeground(new java.awt.Color(255, 255, 255));
        lblcuenta.setText("Cuenta de Usuario:");

        lblusuario.setFont(new java.awt.Font("Trebuchet MS", 3, 26)); // NOI18N
        lblusuario.setForeground(new java.awt.Color(51, 51, 51));
        lblusuario.setText("Ingrese Usuario:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblcuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblusuario)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcuenta)
                    .addComponent(lblusuario))
                .addContainerGap())
        );

        lblsald.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        lblsald.setForeground(new java.awt.Color(51, 51, 51));
        lblsald.setText("Saldo:");

        lblseleccionar.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        lblseleccionar.setForeground(new java.awt.Color(51, 51, 51));
        lblseleccionar.setText("Seleccione:");

        lblvalor.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        lblvalor.setForeground(new java.awt.Color(51, 51, 51));
        lblvalor.setText("Valor:");

        lbsaldo.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lbsaldo.setForeground(new java.awt.Color(51, 51, 51));

        buttonGroup1.add(rdbdeposito);
        rdbdeposito.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        rdbdeposito.setText("Deposito");

        buttonGroup1.add(rdbretiro);
        rdbretiro.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        rdbretiro.setText("Retiro");

        txtvalor.setBackground(new java.awt.Color(153, 153, 255));
        txtvalor.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N

        btnregistrarse.setBackground(new java.awt.Color(153, 153, 255));
        btnregistrarse.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        btnregistrarse.setText("Registrarse");

        lblsaldo.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        lblsaldo.setText("_______");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblvalor)
                        .addGap(33, 33, 33)
                        .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnregistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblsald)
                                .addGap(8, 8, 8)
                                .addComponent(lblsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbsaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblseleccionar)
                                .addGap(18, 18, 18)
                                .addComponent(rdbdeposito)
                                .addGap(18, 18, 18)
                                .addComponent(rdbretiro)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsald)
                    .addComponent(lbsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblseleccionar)
                    .addComponent(rdbdeposito)
                    .addComponent(rdbretiro))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblvalor)
                    .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnregistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLblusuario() {
        return lblusuario;
    }

    public void setLblusuario(JLabel lblusuario) {
        this.lblusuario = lblusuario;
    }

    public JButton getBtnregistrarse() {
        return btnregistrarse;
    }

    public void setBtnregistrarse(JButton btnregistrarse) {
        this.btnregistrarse = btnregistrarse;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public void setButtonGroup1(ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JLabel getLblsaldo() {
        return lblsaldo;
    }

    public void setLblsaldo(JLabel lblsaldo) {
        this.lblsaldo = lblsaldo;
    }

    public JRadioButton getRdbdeposito() {
        return rdbdeposito;
    }

    public void setRdbdeposito(JRadioButton rdbdeposito) {
        this.rdbdeposito = rdbdeposito;
    }

    public JRadioButton getRdbretiro() {
        return rdbretiro;
    }

    public void setRdbretiro(JRadioButton rdbretiro) {
        this.rdbretiro = rdbretiro;
    }

    public JTextField getTxtvalor() {
        return txtvalor;
    }

    public void setTxtvalor(JTextField txtvalor) {
        this.txtvalor = txtvalor;
    }
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregistrarse;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblcuenta;
    private javax.swing.JLabel lblsald;
    private javax.swing.JLabel lblsaldo;
    private javax.swing.JLabel lblseleccionar;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JLabel lblvalor;
    private javax.swing.JLabel lbsaldo;
    private javax.swing.JRadioButton rdbdeposito;
    private javax.swing.JRadioButton rdbretiro;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables
}
